# Application name
APP = test

# Application source files
APP_SRCS = NN.c

# Application includes
APP_INC =

# Compiler flags
APP_CFLAGS = 

# Linker flags
APP_LDFLAGS =

# Custom linker script if needed
APP_LINK_SCRIPT =

# Path to the PMSIS rules makefile


include $(RULES_DIR)/pmsis_rules.mk

